### ISSUE TITLE
async requests

### ISSUE THREAD

**Issue by kokozaurz** [realgam3/pymultitor#12]
Hi,

Thanks for this tool. 

Curious - is it possible to implement something like asyncio to do concurrent requests at the same time, therefore increasing speed?

**Comment by realgam3** [comment]
It is possible but the algorithm should be little bit different,
I need to name every tor node with a unique identifier and save the name when i send the request that way i will know if a bad response came out what node caused it... (if i will not make identifiers i will find myself changing identity few times because more then one response came with the same key to change identity)

Its something i prepare to do in the long run (its also in my slides) but it could take time (I don't want to break it before blackhat)
