### ISSUE TITLE
Invalid Syntax: Line 88 (running pymultitor.py directly as python2.)

### ISSUE THREAD

**Issue by bustnugget** [realgam3/pymultitor#32]
Hi,

I'm having quite a few problems.

If I run pymultitor as python3, I get this list of errors...

https://imgur.com/a/hSBuVUG

However, by running the python file directly as python2, I only get a syntax error on line 88.  No idea why or where to get started with fixing that

https://imgur.com/a/I6fgfUI

Attempting to run as sudo, re-installing all the requirements, restarting, all the basic, beginner-friendly stuff I've already attempted.  Not seeing any changes or fixes though.

Thank you!

**Comment by realgam3** [comment]
I’m sorry but I can’t help you with that,
The issue you show me is an issue with mitmproxy so I guess you need to
open a bug to mitmproxy about it.

Maybe pip install Django will fix it.

The second issue is because It’s a python3 script and I dropped support for
Python 2.

But you can use the docker file to build yourself a container….
